function createfigure(YMatrix1)
%CREATEFIGURE4(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Dec-2021 13:04:47

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',3,'Parent',axes1);
set(plot1(1),'DisplayName','Método Jacobi');
set(plot1(2),'DisplayName','Método Doolittle','LineStyle','-.');
set(plot1(3),'DisplayName','Método Gram-Schmidt','LineStyle',':',...
    'Color',[0.392156862745098 0.831372549019608 0.0745098039215686]);

% Create ylabel
ylabel({'Valor'},'FontSize',16);

% Create xlabel
xlabel({'Iteración'},'FontSize',16);

% Create title
title('Valores Promedios entre técnicas','FontSize',16);

hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',14);

