function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 10-Dec-2021 06:13:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'LineWidth',2,'Parent',axes1);
set(plot1(1),'DisplayName','Error Norma 1',...
    'Color',[0.200000002980232 0.600000023841858 1]);
set(plot1(2),'DisplayName','Error Norma euclídea',...
    'Color',[0 0.600000023841858 0.600000023841858]);
set(plot1(3),'DisplayName','Error Norma infinito','Color',[1 0 0]);

% Create ylabel
ylabel({'Error'},'FontSize',20);

% Create xlabel
xlabel('Iteración','FontSize',20);

% Create title
title('Medidas de Error para F(X):','FontSize',20);

hold(axes1,'off');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.769791666666667 0.731147540983607 0.129861111111111 0.175956284153005],...
    'FontSize',12);

